---
title: "DNA of Tourist destinations"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(d3heatmap)
library(DT)
library(factoextra)

destinations <- read.csv("results/clusters.csv", row.names = 2, encoding = 'latin1')
names(destinations)

cluster_viz <- readRDS("results/kmeans_viz.rds")

```

Column {data-width=400}
-----------------------------------------------------------------------

### Similar destinations (k-means)

```{r}
cluster_viz
```


Column {data-width=600}
-----------------------------------------------------------------------

### Comparing Tourist Destinations in Ecuador by their attraction's types

```{r}
d3heatmap(t(destinations[2:9]), scale = "column", dendrogram = 'none', 
          xaxis_font_size = '8pt',
          yaxis_font_size = '10pt',
          colors = 'GnBu')
```


### Data table

```{r}
datatable(destinations[2:9]) %>%
  formatRound(names(destinations)[2:9], 2)
```

